language: go

sudo: required

go:
  - 1.12

services:
  - docker

before_install:
  - echo "======= before install ====="

# skip install which defaults to running `make` for go languages
script: true

stages:
  # runs every time but on tags
  - name: test
    if: NOT (tag =~ /^v([0-9]+)\.([0-9]+)\.([0-9]+).*$/)
  # runs on push to master (e.g. PR merge)
  - name: deploy-release-candidate
    if: type = push AND branch = master
  # runs on tag
  - name: deploy-release
    if: type = push AND tag =~ /^v([0-9]+)\.([0-9]+)\.([0-9]+).*$/

jobs:
  include:
    - stage: test
      name: job1
      before_script: make setup install dind
      script: make check

    - stage: deploy-release-candidate
      deploy:
        - provider: script
          skip_cleanup: true
          script: make setup install release
          on:
            # assumes this stage is only included on the correct branch or tag
            all_branches: true

    - stage: deploy-release
      deploy:
        - provider: script
          skip_cleanup: true
          script: make release
          on:
            # assumes this stage is only included on the correct branch or tag
            all_branches: true

branches:
  only:
    - master
    - /^v([0-9]+)\.([0-9]+)\.([0-9]+).*$/
