language: bash

before_install:
  - echo "======= before install ====="

stages:
  - name: test
    if: NOT (tag =~ /^v([0-9]+)\.([0-9]+)\.([0-9]+).*$/)
  - name: deploy-release-candidate
    if: type = push AND branch = master
  - name: deploy-release
    if: type = push AND tag =~ /^v([0-9]+)\.([0-9]+)\.([0-9]+).*$/

jobs:
  include:
    - stage: test
      name: job1
      before_script: echo "===== job1 before script ======"
      script: echo "===== job1 ======"

    - stage: deploy-release-candidate
      deploy:
        - provider: script
          skip_cleanup: true
          script: make setup install release
          on:
            # assumes this stage is only included on the correct branch or tag
            all_branches: true

    - stage: deploy-release
      deploy:
        - provider: script
          skip_cleanup: true
          script: make release
          on:
            # assumes this stage is only included on the correct branch or tag
            all_branches: true

branches:
  only:
    - master
    - /^v([0-9]+)\.([0-9]+)\.([0-9]+).*$/
