language: bash

before_install:
  - echo "======= before install ====="

install: echo "======= install ====="

jobs:
  include:
    - stage: test
      name: job1
      before_script: echo "===== job1 before script ======"
      script: echo "===== job1 ======"

    - stage: test
      name: job2
      script: echo "===== job2 ======"

deploy:
  - provider: script
    skip_cleanup: true
    script: echo "=====  deploy ===="
    on:
      tags: true

# tag version following semantic versioning - e.g. v0.70.0-alpha
# regexp expression simplified for readability
branches:
  only:
    - master
    - /^v([0-9]+)\.([0-9]+)\.([0-9]+).*$/
