language: bash

before_install:
  - echo "======= before install ====="

install: echo "======= install ====="

stages:
  - name: test
    if: NOT (tag =~ /^v([0-9]+)\.([0-9]+)\.([0-9]+).*$/)
  - name: deploy-release-candidate
    if: type = push AND branch = master
  - name: deploy-release
    if: type = push AND tag =~ /^v([0-9]+)\.([0-9]+)\.([0-9]+).*$/

jobs:
  include:
    - stage: test
      name: job1
      before_script: echo "===== job1 before script ======"
      script: echo "===== job1 ======"

    - stage: test
      name: job2
      script: echo "===== job2 ======"

    - stage: deploy-release-candidate
      deploy:
        - provider: script
          skip_cleanup: true
          script: echo "=====  deploy release-candidate ===="
          on:
            all_branches: true

    - stage: deploy-release
      deploy:
        - provider: script
          skip_cleanup: true
          script: echo "=====  deploy release ===="
          on:
            all_branches: true

# tag version following semantic versioning - e.g. v0.70.0-alpha-1
# regexp expression simplified for readability - see full regexp here: https://regexr.com/39s32
branches:
  only:
    - master
    - /^v([0-9]+)\.([0-9]+)\.([0-9]+).*$/
